name: marianmemories
description: A new Flutter project for college journal activities.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  animate_do: ^3.3.4
  line_awesome_flutter: ^2.0.0
  get: ^4.6.5
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  cloud_firestore: ^5.6.2
  firebase_storage: ^12.4.1
  http: ^1.2.2
  intl: ^0.20.1
  image_picker: ^1.1.2
  lottie: ^3.3.1
  video_player: ^2.4.7
  speech_to_text: ^7.0.0
  chewie: ^1.10.0
  permission_handler: ^11.3.1
  pdf: ^3.11.3
  path_provider: ^2.1.5
  share: ^2.0.4
  open_file: ^3.5.10

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
