// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDorgy2i21XxVcaYLYs4VTOIVOmw6TPovk',
    appId: '1:122509279770:web:ee2517e30273920a6647a3',
    messagingSenderId: '122509279770',
    projectId: 'proj-227cc',
    authDomain: 'proj-227cc.firebaseapp.com',
    storageBucket: 'proj-227cc.firebasestorage.app',
    measurementId: 'G-DBD1CETFFE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFv4Zq7i_IbWFrccqeOZgSOilV4u3EPrY',
    appId: '1:122509279770:android:cd5f5ab129e51c546647a3',
    messagingSenderId: '122509279770',
    projectId: 'proj-227cc',
    storageBucket: 'proj-227cc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATbEWG1zFphA2FWH3ecWH_NgiP_jgOc0U',
    appId: '1:122509279770:ios:23b7733777fbb7576647a3',
    messagingSenderId: '122509279770',
    projectId: 'proj-227cc',
    storageBucket: 'proj-227cc.firebasestorage.app',
    iosBundleId: 'com.example.marianmemories',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATbEWG1zFphA2FWH3ecWH_NgiP_jgOc0U',
    appId: '1:122509279770:ios:23b7733777fbb7576647a3',
    messagingSenderId: '122509279770',
    projectId: 'proj-227cc',
    storageBucket: 'proj-227cc.firebasestorage.app',
    iosBundleId: 'com.example.marianmemories',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDorgy2i21XxVcaYLYs4VTOIVOmw6TPovk',
    appId: '1:122509279770:web:1549aca12dd53f786647a3',
    messagingSenderId: '122509279770',
    projectId: 'proj-227cc',
    authDomain: 'proj-227cc.firebaseapp.com',
    storageBucket: 'proj-227cc.firebasestorage.app',
    measurementId: 'G-CVDCY9T0M9',
  );

}